title: Sagar Sahoo
logo: /assets/img/SagarSahoo.jpg

description:
  <p align="center">
  <a href="https://github.com/sagar220887">GitHub</a>
  
  <br>   
  Working as an aspiration towards AI and ML.
  <br>
  </p>
theme: jekyll-theme-minimal
